In [ ]:
import numpy as np

# **1. Numpy:**
a. Using NumPy create random vector of size 15 having only Integers in the range 1-20.
1. Reshape the array to 3 by 5
2. Print array shape.
3. Replace the max in each row by 0


In [ ]:
import numpy as np
random_vector = np.random.randint(1,21,size=15)

In [ ]:
random_vector

array([11, 17,  7, 15,  4, 10, 13,  3,  3, 18, 20,  2, 18, 13,  3])

In [ ]:
reshaped_vector = random_vector.reshape(3,5)

In [ ]:
reshaped_vector.shape

(3, 5)

In [ ]:
print(reshaped_vector)

[[11 17  7 15  4]
 [10 13  3  3 18]
 [20  2 18 13  3]]


In [ ]:
vector_replaced_with_Zero = np.where(reshaped_vector == np.max(reshaped_vector,axis=1,keepdims=True),0,reshaped_vector)

In [ ]:
vector_replaced_with_Zero

array([[11,  0,  7, 15,  4],
       [10, 13,  3,  3,  0],
       [ 0,  2, 18, 13,  3]])

b. Create a 2-dimensional array of size 4 x 3 (composed of 4-byte integer elements), also print the shape, type and data
type of the array.

In [ ]:
array_2d = np.random.randint(1,21,size=(4,3),dtype=np.int32)

In [ ]:
array_2d.shape

(4, 3)

In [ ]:
array_2d.dtype

dtype('int32')

c. Write a program to compute the eigenvalues and right eigenvectors of a given square array given below:
[[ 3 -2]
[ 1 0]]

In [ ]:
square_array = np.array([[3,-2],[1,0]])
eigenvalues,eigenvectors = np.linalg.eig(square_array)
print(eigenvalues)
print(eigenvectors)

[2. 1.]
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


d. Compute the sum of the diagonal element of a given array.
[[0 1 2]
[3 4 5]]

In [ ]:
array_diag = np.array([[0,1,2],[3,4,5]])
print(array_diag)
np.trace(array_diag)

[[0 1 2]
 [3 4 5]]


np.int64(4)

e. Write a NumPy program to create a new shape to an array without changing its data.
Reshape 3x2:
[[1 2]
[3 4]
[5 6]]
Reshape 2x3:
[[1 2 3]
[4 5 6]]

In [ ]:
array_3x2 = np.array([[1, 2],[3, 4],[5, 6]])
print(array_3x2)
array_2x3 = array_3x2.reshape(2, 3)
print(array_2x3)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


[https://drive.google.com/file/d/1WXRLZY1AxhxyWahpj9b7Qi2T7lBRB2yr/view?usp=sharing](https://drive.google.com/file/d/1WXRLZY1AxhxyWahpj9b7Qi2T7lBRB2yr/view?usp=sharing)